version: '3'

networks:
  connection:
    driver: bridge

services:
  node:
    build: .
    container_name: school
    ports:
    - "80:3000"
    - "443:443"
    volumes:
    - ./:/var/www
    links:
    - db
    networks:
    - connection

  db:
    image: mysql:8.0
    container_name: school_db
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=school
    volumes:
    - /var/lib/mysql  
    networks:
    - connection
    ports:
      - "8081:3306"